<?xml version="1.0" encoding="UTF-8"?>
<config>
    <modules>
        <Overcart_BarcodeTesting>
            <version>0.0.1</version>
        </Overcart_BarcodeTesting>
    </modules>
    <frontend>
        <routers>
            <barcode>
                <use>standard</use>
                <args>
                    <module>Overcart_BarcodeTesting</module>
                    <frontName>barcode</frontName>
                </args>
            </barcode>
        </routers>
    </frontend>
    <global>
     <events>
            <controller_action_postdispatch_adminhtml_sales_order_shipment_print>
                <observers>
                    <observer_printShipments>
                        <type>singleton</type>
                        <class>Overcart_BarcodeTesting_Model_Observer</class>
                        <method>printShipment</method>
                    </observer_printShipments>
                </observers>
            </controller_action_postdispatch_adminhtml_sales_order_shipment_print>
            <ves_shipment_pdfpro_data_prepare_after>
                <observers>
                    <observer_easypdfShipment>
                        <type>singleton</type>
                        <class>Overcart_BarcodeTesting_Model_Observer</class>
                        <method>easypdf_shipmentObserver</method>
                    </observer_easypdfShipment>
                </observers>
            </ves_shipment_pdfpro_data_prepare_after>
            <ves_invoice_pdfpro_data_prepare_after>
                <observers>
                    <observer_easypdfInvoice>
                        <type>singleton</type>
                        <class>Overcart_BarcodeTesting_Model_Observer</class>
                        <method>easypdf_invoiceObserver</method>
                    </observer_easypdfInvoice>
                </observers>
            </ves_invoice_pdfpro_data_prepare_after>
        </events>
    </global>
</config>